GanafWeb/Controllers/BloggingController.cs
using System;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GanafWeb.Domain;
using GanafWeb.Logic.Abstract;
using GanafWeb.Logic.Concrete;
using GanafWeb.Logic.Constants;

namespace GanafWeb.Controllers
{
    public class BloggingController : Controller
    {
        readonly IBlogger _blogger = new Blogger();
        IRequest request = new Request();

        public ActionResult Home()
        {
            var result = _blogger.GetPosts();
            TempData["Posts"] = result.ToList();
            TempData.Keep("Posts");
            return View();
        }

        public ActionResult Details(int id)
        {
            var result = _blogger.GetPost(id);
            TempData["Post"] = result;
            TempData.Keep("Post");
            var result2 = _blogger.GetPosts();
            TempData["Posts"] = result2.ToList();
            TempData.Keep("Posts");
            return View("BlogDetails");
        }

        public ActionResult Comment(string message, string postId)
        {
            try
            {
                if (!SessionParameters.GetUserAuthenticated())
                {
                    return RedirectToAction("OtherUser", "Home");
                }
                var result = _blogger.Comment(message, int.Parse(postId));
                if (result.Contains("ERROR"))
                {
                    ViewBag.Status = "ERROR";
                    ViewBag.StatusMesage = result.Substring(0, result.LastIndexOf("?", StringComparison.Ordinal));
                }
                else
                {
                    ViewBag.Status = "SUCCESS";
                    ViewBag.StatusMesage = result;
                }
            }
            catch (Exception)
            {
                //Ignored
            }
            return View("BlogDetails");
        }

        [HttpGet]
        public ActionResult MakePost()
        {
            if (SessionParameters.GetUserAuthenticated() &&
                request.GetUser(SessionParameters.GetCurrentUser()).userType.Trim().Equals(UserTypes.ADMIN))
            {
                var result = _blogger.GetPosts();
                TempData["Posts"] = result.ToList();
                TempData.Keep("Posts");
                return View();
            }
            return RedirectToAction("OtherUser", "Home");
        }

        [HttpPost]
        public ActionResult MakePost(string postedBy, string intro, string topic, string body, HttpPostedFileBase picture)
        {
            if (SessionParameters.GetUserAuthenticated() &&
                request.GetUser(SessionParameters.GetCurrentUser()).userType.Trim().Equals(UserTypes.ADMIN))
            {
                try
                {
                    if (picture != null)
                    {
                        var extension = Path.GetExtension(picture.FileName);

                        var pic = DateTime.Now.Year.ToString() + DateTime.Now.Month.ToString() +
                                           DateTime.Now.Day.ToString() + DateTime.Now.Hour.ToString() +
                                           DateTime.Now.Minute.ToString() + DateTime.Now.Second.ToString();

                        var path = Path.Combine(Server.MapPath("~/Content/Uploads/Photos/"), pic + extension);
                        picture.SaveAs(path);

                        var scaled = Utils.Scale(Image.FromFile(path), 261, 193);
                        System.IO.File.Delete(path);
                        scaled.Save(path);
                        var picture2 = Utils.Scale(Image.FromFile(path), 75, 75);
                        var path2 = Path.Combine(Server.MapPath("~/Content/Uploads/Photos/Small/"), pic + extension);
                        picture2.Save(path2);

                        var p = new post
                        {
                            postedBy = postedBy,
                            topic = topic,
                            intro = intro,
                            body = body,
                            image = (pic + extension),
                            postDate = DateTime.Now
                        };
                        var r = _blogger.AddPost(p);
                        if (r.Contains("ERROR"))
                        {
                            ViewBag.Status = "ERROR";
                            ViewBag.StatusMessage = r.Substring(0, r.LastIndexOf("?", StringComparison.Ordinal));
                        }
                        else
                        {
                            ViewBag.Status = "SUCCESS";
                            ViewBag.StatusMessage = r;
                        }
                        var result = _blogger.GetPosts();
                        TempData["Posts"] = result.ToList();
                        TempData.Keep("Posts");
                    }
                }
                catch (Exception)
                {
                    //Ignore
                }
                return View();
            }
            return RedirectToAction("OtherUser", "Home");
        }
        
        [HttpGet]
        public ActionResult EditPost(int id)
        {
            if (SessionParameters.GetUserAuthenticated() &&
                request.GetUser(SessionParameters.GetCurrentUser()).userType.Trim().Equals(UserTypes.ADMIN))
            {
                var r = _blogger.GetPosts();
                TempData["Posts"] = r.ToList();
                TempData.Keep("Posts");

                var result = _blogger.GetPost(id);
                TempData["Post"] = result;
                TempData.Keep("Post");
                return View();
            }
            return RedirectToAction("OtherUser", "Home");
        }

        [HttpPost]
        public ActionResult EditPost(string intro, string topic, string body, string postId)
        {
            if (SessionParameters.GetUserAuthenticated() &&
                request.GetUser(SessionParameters.GetCurrentUser()).userType.Trim().Equals(UserTypes.ADMIN))
            {
                var post = _blogger.GetPost(int.Parse(postId));
                post.intro = intro;
                post.topic = topic;
                post.body = body;
                var r = _blogger.ModifyPost(post);
                if (r.Contains("ERROR"))
                {
                    ViewBag.Status = "ERROR";
                    ViewBag.StatusMessage = r.Substring(0, r.LastIndexOf("?", StringComparison.Ordinal));
                }
                else
                {
                    ViewBag.Status = "SUCCESS";
                    ViewBag.StatusMessage = r;
                }
                var result = _blogger.GetPosts();
                TempData["Posts"] = result.ToList();
                TempData.Keep("Posts");
                return View("MakePost");
            }
            return RedirectToAction("OtherUser", "Home");
        }

        public ActionResult DeletePost(int id)
        {
            if (SessionParameters.GetUserAuthenticated() &&
                request.GetUser(SessionParameters.GetCurrentUser()).userType.Trim().Equals(UserTypes.ADMIN))
            {
                var r = _blogger.DeletePost(id);
                if (r.Contains("ERROR"))
                {
                    ViewBag.Status = "ERROR";
                    ViewBag.StatusMessage = r.Substring(0, r.LastIndexOf("?", StringComparison.Ordinal));
                }
                else
                {
                    ViewBag.Status = "SUCCESS";
                    ViewBag.StatusMessage = r;
                }
                var result = _blogger.GetPosts();
                TempData["Posts"] = result.ToList();
                TempData.Keep("Posts");
                return View("MakePost");
            }
            return RedirectToAction("OtherUser", "Home");
        }
    }
}

GanafWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GanafWeb.Domain;
using GanafWeb.Logic.Abstract;
using GanafWeb.Logic.Concrete;
using GanafWeb.Logic.Constants;
using GanafWeb.Models;
using request = GanafWeb.Models.request;

namespace GanafWeb.Controllers
{
    public class HomeController : Controller
    {
        readonly IRequest _request = new Request();
        readonly IContactUs _iContactUs = new ContactUs();

        public ActionResult Index()
        {
            ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";

            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        //public ActionResult Contact()
        //{
        //    ViewBag.Message = "Your contact page.";

        //    return View();
        //}
        [HttpGet]
        public ActionResult MyLogin()
        {
            return View();
        }
        [HttpPost]
        public ActionResult MyLogin(users user)
        {
            GanafDBBEntities1 entity = new GanafDBBEntities1();
            entity.users.Add(user);
            entity.SaveChanges();
            return View();
        }
        [HttpGet]
        public ActionResult ContactUs()
        {
            return View();
        }

        [HttpGet]
        public ActionResult ErrorPage()
        {
            return View("ErrorPage");
        }

        [HttpPost]
        public ActionResult ContactUs(request request)
        {
            
            using (GanafDBBEntities1  entity = new GanafDBBEntities1 ())
            {
                entity.request.Add(request);
                entity.SaveChanges();
            }
          
           
            return View();
        }

        public ActionResult Authenticate(string username, string password)
        {
            try
            {
                var validUsername = System.Configuration.ConfigurationManager.AppSettings.Get("AuthenticationUsername");
                var validPassword = System.Configuration.ConfigurationManager.AppSettings.Get("AuthenticationPassword");
                if (!username.Equals(validUsername) || !password.Equals(validPassword))
                {
                    var result = _request.Authenticate(username, password);
                    if (result.Contains("?ERROR"))
                    {
                        ViewBag.Status = "ERROR";
                        ViewBag.StatusMessage = result.Substring(0, result.LastIndexOf("?", StringComparison.Ordinal));
                    }
                    else
                    {
                        return View("Index");
                    }
                    return View("OtherUsers");
                }
                _request.AuthenticateAdmin(validUsername, validPassword);
                return View("Index");
            }
            catch (Exception)
            {
                return null;
            }
        }

        public ActionResult Register(string firstname, string lastname, string email, string phone, string username, string password)
        {
            try
            {
                var user = new user
                {
                    firstname = firstname,
                    lastname = lastname,
                    email = email,
                    phone = phone,
                    username = username,
                    password = password,
                    userType = UserTypes.OTHER
                };
                _iContactUs.Register(user);
                ViewBag.Status = "SUCCESS";
                ViewBag.StatusMessage = "Registration successful";
            }
            catch (Exception)
            {
                ViewBag.Status = "ERROR";
                ViewBag.StatusMessage = "Something went wrong. Please retry";
            }
            return View("OtherUsers");
        }

        [HttpGet]
        public ActionResult OtherUser()
        {
            return View("OtherUsers");
        }
    }
}

GanafWeb/Views/Blogging/BlogDetails.cshtml
@using System.Collections
@using GanafWeb.Domain
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*@section facebookScript
{
    <script type="text/javascript">
        window.fbAsyncInit = function () {
            FB.init({
                appId: '368705343338789',
                xfbml: true,
                version: 'v2.4'
            });
        };

        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) { return; }
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
}*@

@section featured
{
    <header class="main-header">
        <div class="container">
            <h1 class="page-title">Blog Item</h1>

            <ol class="breadcrumb pull-right">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Blog", "Home", "Blogging")</li>
                <li class="active">Blog Item</li>
            </ol>
        </div>
    </header>
    <div class="container">
        <div class="row">
            @if (ViewBag.Status == "ERROR")
            {
                <div class="alert alert-danger">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <strong><i class="fa fa-times"></i>Error!</strong>@ViewBag.StatusMessage
                </div>
            }
            else if (ViewBag.Status == "SUCCESS")
            {
                <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <strong><i class="fa fa-times"></i>Success!</strong> @ViewBag.StatusMessage
                </div>
            }

        </div>
        <div class="row">
            <div class="col-md-8">
                @{
                    var post = TempData["Post"] as post;
                    <section>
                        <h2 class="page-header no-margin-top">@post.topic</h2>
                        <img src="@Url.Content("~/Content/Uploads/Photos/" + post.image)" class="img-responsive imageborder" alt="Image">
                        <br/>
                        <blockquote class="blockquote-">
                            <p>@post.intro</p>
                        </blockquote>
                        <div>
                            <p>@post.body</p>
                        </div>
                    </section>
                    <section>
                        <div class="panel panel-default">
                            <div class="panel-body">
                                @* Twitter *@
                                <a href="https://twitter.com/share" class="social-icon-ar sm no-margin-bottom twitter">
                                    <i class="fa fa-twitter"></i>
                                </a>
                                <script>
                                    !function (d, s, id) {
                                        var js,
                                            fjs = d.getElementsByTagName(s)[0],
                                            p = /^http:/.test(d.location) ? 'http' : 'https';
                                        if (!d.getElementById(id)) {
                                            js = d.createElement(s);
                                            js.id = id;
                                            js.src = p + '://platform.twitter.com/widgets.js';
                                            fjs.parentNode.insertBefore(js, fjs);
                                        }
                                    }
                                    (document, 'script', 'twitter-wjs');
                                </script>
                                @*<a href="#" class="social-icon-ar sm no-margin-bottom facebook"><i class="fa fa-facebook"></i></a>*@
                                @* Google plus *@
                                <script src="https://apis.google.com/js/platform.js" async defer></script>
                                <div class="g-plus" data-action="share">
                                    <i class="fa fa-google-plus"></i>
                                </div>
                                @*<a class="social-icon-ar sm no-margin-bottom rss">
                                    <div
                                        class="fb-like"
                                        data-share="true"
                                        data-width="450"
                                        data-show-faces="true">
                                    </div>
                                </a>*@
                            </div>
                        </div>
                    </section>
                    <section>
                        <h2 class="section-title">Comments</h2>
                        <ul class="list-unstyled">
                            @{
                                var comments = post.Comments;
                                if (comments.Count != 0)
                                {
                                    foreach (var comment in comments)
                                    {
                                        <li class="comment">
                                            <div class="panel panel-default">
                                                <div class="panel-body">
                                                    <p>@comment.comment1</p>
                                                </div>
                                                <div class="panel-footer">
                                                    <div class="row">
                                                        <div class="col-lg-10 col-md-9 col-sm-8">
                                                            <i class="fa fa-user"></i><a href="#">@comment.user.firstname</a> <i class="fa fa-clock-o"></i>@comment.commentDate
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                    }
                                }
                                else
                                {
                                    <div class="panel panel-danger">
                                        <div class="panel-title"></div>
                                        <div class="panel-body">
                                            <p class="lead lead-lg">There are no comments yet</p>
                                        </div>
                                    </div>
                                }
                            }

                        </ul>
                    </section>
                    <!-- comments -->
                    <section class="comment-form">
                        <h2 class="section-title">Leave a Comment</h2>
                        @using (Html.BeginForm("Comment", "Blogging"))
                        {
                            <div class="form-group">
                                <label for="inputMessage">Mesagge</label>
                                <textarea class="form-control" id="inputMessage" rows="6" name="message"></textarea>
                            </div>
                            <input type="hidden" value="@post.id" name="postId"/>
                            <button type="submit" class="btn btn-ar pull-right btn-primary">Submit</button>
                        }
                    </section>
                    <!-- comment-form -->


                }
            </div>
            <div class="col-md-4">
                <aside class="sidebar">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <i class="fa fa-comments"></i>Posts
                        </div>
                        <div class="panel-body">
                            <ul class="comments-sidebar">
                                @{
                                    IEnumerable<GanafWeb.Domain.post> posts = TempData["Posts"] as List<GanafWeb.Domain.post>;
                                    if (posts != null)
                                    {
                                        foreach (var p in posts)
                                        {
                                            <li>
                                                <img src="@Url.Content("~/Content/Uploads/Photos/Small/" + p.image)" class="img-responsive" alt="Image">
                                                <h4>@Html.ActionLink(p.topic, "Details", "Blogging", new{id = @p.id}, null)</h4>
                                                <p>@p.intro.Substring(0, p.intro.Length/2) ...</p>
                                            </li>
                                            <hr class="dotted"/>
                                        }
                                    }
                                }
                            </ul>
                        </div>
                    </div>

                </aside>
                <!-- Sidebar -->
            </div>
        </div>
    </div>
    <!-- container  -->

}

GanafWeb/Views/Blogging/EditPost.cshtml
@using GanafWeb.Domain
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section featured
{
    <header class="main-header">
        <div class="container">
            <h1 class="page-title">Blog Item</h1>

            <ol class="breadcrumb pull-right">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Blog", "Home", "Blogging")</li>
                <li class="active">Blog Item</li>
            </ol>
        </div>
    </header>
    <div class="container">
        <div class="row">
            @if (ViewBag.Status == "ERROR")
            {
                <div class="alert alert-danger">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <strong><i class="fa fa-times"></i>Error!</strong>@ViewBag.StatusMessage
                </div>
            }
            else if (ViewBag.Status == "SUCCESS")
            {
                <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <strong><i class="fa fa-times"></i>Success!</strong> @ViewBag.StatusMessage
                </div>
            }

        </div>
        <div class="row">
            @{
                <div class="col-md-8">
                    @{
                        var pp = TempData["post"] as post;
                        <section class="comment-form">
                            <h2 class="section-title">Add a new post</h2>
                            @using (Html.BeginForm("EditPost", "Blogging", FormMethod.Post))
                            {

                                <input type="hidden" name="postId" value="@pp.id">
                                <div class="form-group">
                                    <label for="inputEmail">Topic:</label>
                                    <input type="text" name="topic" value="@pp.topic" class="form-control" id="inputEmail" placeholder="example@example.com">
                                </div>
                                <div class="form-group">
                                    <label for="inputMessage">Intro:</label>
                                    <textarea class="form-control" name="intro" id="inputIntro" rows="3"></textarea>
                                </div>
                                <div class="form-group">
                                    <label for="inputMessage">Body:</label>
                                    <textarea class="form-control" name="body" id="inputMessage" rows="6"></textarea>
                                </div>
                                <button type="submit" class="btn btn-ar pull-right btn-primary">Submit</button>
                                <br/>
                                <br/>
                                <div class="panel panel-primary">
                                    <div class="panel-title">
                                        <h3>Post Introduction</h3>
                                    </div>
                                    <div class="panel-body">
                                        <p>@pp.intro</p>
                                    </div>
                                </div>
                                <br />
                                <div class="panel panel-primary">
                                    <div class="panel-title">
                                        <h3>Post Body</h3>
                                    </div>
                                    <div class="panel-body">
                                        <p>@pp.body</p>
                                    </div>
                                </div>
                            }
                        </section>
                        <!-- comment-form -->
                    }



                </div>
                <div class="col-md-4">
                    <aside class="sidebar">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <i class="fa fa-comments"></i>Posts
                            </div>
                            <div class="panel-body">
                                <ul class="comments-sidebar">
                                    @{
                                        IEnumerable<GanafWeb.Domain.post> posts = TempData["Posts"] as List<GanafWeb.Domain.post>;
                                        if (posts != null)
                                        {
                                            foreach (var p in posts)
                                            {
                                                <li>
                                                    <img src="@Url.Content("~/Content/Uploads/Photos/Small/" + p.image)" class="img-responsive" alt="Image">
                                                    <h4>@Html.ActionLink(p.topic, "Details", "Blogging")</h4>
                                                    <p>@p.intro.Substring(0, p.intro.Length/2) ...</p>
                                                    <div class="col-sm-2">
                                                        <span class="col-sm-2">@Html.ActionLink("Edit Post", "EditPost", "Blogging", new {id = @p.id}, htmlAttributes: new {@class = "btn btn-ar btn-primary"})</span>
                                                        
                                                    </div>
                                                    <div class="col-sm-2">
                                                        <span class="col-sm-2 col-sm-offset-2">@Html.ActionLink("Delete Post", "DeletePost", "Blogging", new {id = @p.id}, htmlAttributes: new {@class = "btn btn-ar btn-primary"})</span>
                                                    </div>
                                                </li>
                                                <hr class="dotted"/>
                                            }
                                        }
                                    }
                                </ul>
                            </div>
                        </div>

                    </aside>
                    <!-- Sidebar -->
                </div>
            }
        </div>
    </div>
    <!-- container  -->
}

GanafWeb/Views/Blogging/Home.cshtml
@using GanafWeb.Domain
@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section featured
{
    <header class="main-header">
        <div class="container">
            <h1 class="page-title">Blog Home</h1>

            <ol class="breadcrumb pull-right">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li class="active">Blog Home</li>
            </ol>
        </div>
    </header>

    <div class="container">
        <div class="row masonry-container">
            @{
                //var a = TempData["Posts"];
                var allPost = TempData["Posts"] as List<post>;
                //IEnumerable<post> allPost = a as List<post>;
                if (allPost != null)
                {
                    foreach (var post in allPost)
                    {
                        <div class="col-md-4 col-sm-6 masonry-item blog-item">
                            <div class="thumbnail">
                                <img src="@Url.Content("~/Content/Uploads/Photos/" + post.image)" class="img-responsive" alt="Image">
                                <div class="caption">
                                    <h3>@post.topic</h3>
                                    <p>@post.intro</p>
                                    <hr class="dotted">
                                    @*<span class="autor-post">
                                    <img src="~/Content/assets/img/demo/w10.jpg" alt="">
                                    by <a href="#">adrigm</a>
                                </span>*@
                                    @Html.ActionLink("Read more", "Details", "Blogging", new{id = @post.id}, htmlAttributes: new{@class = "btn btn-ar btn-primary pull-right"})
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                    }
                }
                else
                {
                    <p>There are no posts yet.</p>
                }
            }
        </div>
        <!-- masonry-container  -->

        @*<div class="row">
            <section class="text-center">
                <ul class="pagination pagination-lg pagination-border">
                    <li class="disabled"><a href="#">&laquo;</a></li>
                    <li class="active"><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">5</a></li>
                    <li><a href="#">6</a></li>
                    <li><a href="#">7</a></li>
                    <li><a href="#">8</a></li>
                    <li><a href="#">9</a></li>
                    <li><a href="#">10</a></li>
                    <li><a href="#">&raquo;</a></li>
                </ul>
            </section>
        </div>*@
        <!-- row -->
    </div>
    <!-- container  -->

}